<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="waver_gazebo">

  <xacro:include filename="$(find waver_description)/urdf/util.xacro" />

  <gazebo reference="base_link">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <selfCollide>false</selfCollide>
    <material>Gazebo/DarkGrey</material>
  </gazebo>

  <gazebo reference="top_shell_link">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <selfCollide>false</selfCollide>
    <material>Gazebo/DarkGrey</material>
  </gazebo>

  <gazebo reference="accessories_link">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <selfCollide>false</selfCollide>
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="accessories1_link">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <selfCollide>false</selfCollide>
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="imu_link">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <selfCollide>false</selfCollide>
    <material>Gazebo/Orange</material>
  </gazebo>

  <gazebo reference="oled_screen_link">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <selfCollide>false</selfCollide>
    <material>Gazebo/BlueGlow</material>
  </gazebo>

  <gazebo reference="wheel_back_left_link">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <selfCollide>false</selfCollide>
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="wheel_front_left_link">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <selfCollide>false</selfCollide>
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="wheel_front_right_link">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <selfCollide>false</selfCollide>
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="wheel_back_right_link">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <selfCollide>false</selfCollide>
    <material>Gazebo/Black</material>
  </gazebo>

    <!-- <gazebo>
      <plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
        <ros>
          <namespace></namespace>
          <remapping>cmd_vel:=cmd_vel</remapping>
        </ros>
        <update_rate>100.0</update_rate>
        <left_joint>wheel_front_left_joint</left_joint>
        <right_joint>wheel_front_right_joint</right_joint>
        <wheel_separation>${wheel_separation}</wheel_separation>
        <wheel_diameter>${wheel_radius * 2}</wheel_diameter>
        <robot_base_frame>base_footprint</robot_base_frame>
        <odom_frame>odom</odom_frame>
        <publish_odom>true</publish_odom>
        <publish_odom_tf>true</publish_odom_tf>
      </plugin>
    </gazebo> -->
    <gazebo>
      <plugin name="four_wheel_drive_controller" filename="libwaver_description.so">
        <ros>
          <argument>cmd_vel:=/cmd_vel</argument>
        </ros>
      </plugin>
    </gazebo>

</robot>
